apiVersion: apps/v1
kind: Deployment
metadata:
  name: project6-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project6
  template:
    metadata:
      labels:
        app: project6
    spec:
      containers:
      - name: project6
        image: blerinabombaj/project6:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: project6-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: project6
